import type { TravelRequest, Manager } from "@/types/travel"

export const mockTravelRequests: TravelRequest[] = [
  // Pending travel requests
  {
    id: 1,
    user_id: 4,
    user: {
      id: 4,
      name: "Emily Davis",
      email: "emily.davis@workhub.com",
    },
    title: "New York Client Meeting",
    destination: "New York, NY",
    customer_project: "Fortune 500 Client Presentation",
    luggage_needed: true,
    preferred_travel_time: "morning",
    departure_date: "2024-04-15",
    return_date: "2024-04-18",
    purpose: "Client presentation and contract negotiation with Fortune 500 company",
    status: "pending",
    estimated_cost: 2850.0,
    actual_cost: null,
    manager_id: 2,
    manager: {
      id: 2,
      name: "Sarah Johnson",
      email: "sarah.johnson@workhub.com",
    },
    manager_comments: null,
    additional_notes: "Need to prepare presentation materials before the trip",
    created_at: "2024-03-10T14:30:00Z",
    updated_at: "2024-03-10T14:30:00Z",
  },
  {
    id: 2,
    user_id: 7,
    user: {
      id: 7,
      name: "David Martinez",
      email: "david.martinez@workhub.com",
    },
    title: "SXSW Tech Conference",
    destination: "Austin, TX",
    customer_project: "Market Research",
    luggage_needed: true,
    preferred_travel_time: "afternoon",
    departure_date: "2024-04-22",
    return_date: "2024-04-25",
    purpose: "SXSW Tech Conference - market research and networking",
    status: "pending",
    estimated_cost: 1950.0,
    actual_cost: null,
    manager_id: 3,
    manager: {
      id: 3,
      name: "Michael Brown",
      email: "michael.brown@workhub.com",
    },
    manager_comments: null,
    additional_notes: "Will need to book conference tickets separately",
    created_at: "2024-03-12T09:45:00Z",
    updated_at: "2024-03-12T09:45:00Z",
  },
  {
    id: 5,
    user_id: 6,
    user: {
      id: 6,
      name: "Lisa Brown",
      email: "lisa.brown@workhub.com",
    },
    title: "Chicago Trade Show",
    destination: "Chicago, IL",
    customer_project: "Q2 Lead Generation",
    luggage_needed: true,
    preferred_travel_time: "morning",
    departure_date: "2024-04-02",
    return_date: "2024-04-05",
    purpose: "Trade show participation and lead generation activities",
    status: "approved",
    estimated_cost: 1750.0,
    actual_cost: null,
    manager_id: 2,
    manager: {
      id: 2,
      name: "Sarah Johnson",
      email: "sarah.johnson@workhub.com",
    },
    manager_comments: "Important for Q2 sales targets. Approved for full budget.",
    additional_notes: "Booth materials will be shipped separately",
    created_at: "2024-03-08T13:45:00Z",
    updated_at: "2024-03-09T10:20:00Z",
  },

  // Completed travel requests
  {
    id: 6,
    user_id: 9,
    user: {
      id: 9,
      name: "Tom Anderson",
      email: "tom.anderson@workhub.com",
    },
    title: "DevOps Summit",
    destination: "San Francisco, CA",
    customer_project: "Infrastructure Planning",
    luggage_needed: false,
    preferred_travel_time: "morning",
    departure_date: "2024-03-01",
    return_date: "2024-03-03",
    purpose: "DevOps summit and infrastructure planning sessions",
    status: "completed",
    estimated_cost: 1900.0,
    actual_cost: 1875.5,
    manager_id: 3,
    manager: {
      id: 3,
      name: "Michael Brown",
      email: "michael.brown@workhub.com",
    },
    manager_comments: "Great value from the conference. Completed under budget.",
    additional_notes: null,
    created_at: "2024-02-20T15:30:00Z",
    updated_at: "2024-03-04T09:15:00Z",
  },
  {
    id: 7,
    user_id: 4,
    user: {
      id: 4,
      name: "Emily Davis",
      email: "emily.davis@workhub.com",
    },
    title: "Harvard Business Review Summit",
    destination: "Boston, MA",
    customer_project: "Digital Transformation",
    luggage_needed: true,
    preferred_travel_time: "afternoon",
    departure_date: "2024-02-28",
    return_date: "2024-03-02",
    purpose: "Harvard Business Review summit on digital transformation",
    status: "completed",
    estimated_cost: 2200.0,
    actual_cost: 2150.75,
    manager_id: 2,
    manager: {
      id: 2,
      name: "Sarah Johnson",
      email: "sarah.johnson@workhub.com",
    },
    manager_comments: "Excellent networking opportunities. Well executed trip.",
    additional_notes: "Shared learnings with team upon return",
    created_at: "2024-02-15T10:45:00Z",
    updated_at: "2024-03-03T14:30:00Z",
  },

  // Rejected travel request
  {
    id: 8,
    user_id: 7,
    user: {
      id: 7,
      name: "David Martinez",
      email: "david.martinez@workhub.com",
    },
    title: "Miami Team Building",
    destination: "Miami, FL",
    customer_project: "Team Building",
    luggage_needed: true,
    preferred_travel_time: "morning",
    departure_date: "2024-04-08",
    return_date: "2024-04-12",
    purpose: "Beach conference and team building activities",
    status: "rejected",
    estimated_cost: 3200.0,
    actual_cost: null,
    manager_id: 3,
    manager: {
      id: 3,
      name: "Michael Brown",
      email: "michael.brown@workhub.com",
    },
    manager_comments: "Budget constraints for Q1. Please reschedule for Q2 if still relevant.",
    additional_notes: "Team of 5 people",
    created_at: "2024-03-11T12:20:00Z",
    updated_at: "2024-03-12T08:45:00Z",
  },
]

export const mockManagers: Manager[] = [
  {
    id: 1,
    name: "John Smith",
    email: "john.smith@workhub.com",
    department: "Executive",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    email: "sarah.johnson@workhub.com",
    department: "Sales",
  },
  {
    id: 3,
    name: "Michael Brown",
    email: "michael.brown@workhub.com",
    department: "Technology",
  },
  {
    id: 4,
    name: "Jennifer Williams",
    email: "jennifer.williams@workhub.com",
    department: "Marketing",
  },
  {
    id: 5,
    name: "Robert Davis",
    email: "robert.davis@workhub.com",
    department: "Finance",
  },
]
